### ISSUE TITLE
Missing borders?

### ISSUE THREAD

**Issue by beojan** [obnosim/velours#3]
It appears that borders may be missing, or some similar issue may exist, which causes icons (e.g. in the system tray) to be noticeably larger with this plasma theme.

**Comment by beojan** [comment]
See the difference between Velours:
![image](https://cloud.githubusercontent.com/assets/3727925/14226905/efcec374-f8e7-11e5-89ec-1cccd496deda.png)

and Papirus-dark
![image](https://cloud.githubusercontent.com/assets/3727925/14226906/01d95a20-f8e8-11e5-8d20-7b63a9e2c6d8.png)

using the same icons.

**Comment by obnosim** [comment]
I assume you are using Velours 5 with Plasma 5.

There are borders, but they are smaller than in most other themes. This is a design decision.

However, the way Plasma handles tray icons, they should never grow beyond 22x22 px, regardless of the theme. In my current setup, panels are noticeably larger that in your screenshots (48px thick), yet icons have the expected size.

I don't know, but it might be that you seem to be mixing Velours with another theme's icons. I heard this feature was removed from Plasma 5.6 because it was apparently buggy. That might be one of those bugs.

Have you tried using a pure Velours theme and perhaps replacing the icons with the ones from your other theme manually, e.g. by replacing <Velours5>/icons with  <Other>/icons?

**Comment by beojan** [comment]
The issue exists with Velours' own icons too. Also, I did replace the icons manually, not using the customization tab.

I should add that I have a 15.6" 1920x1080 screen. The issue does not appear if I switch my screen resolution to 1366x768.

**Comment by obnosim** [comment]
Thanks for the clarifications. I don't know what's causing this. I have the same resolution and the same screen size, and this is what it looks like to me.
![spectacle ti5036](https://cloud.githubusercontent.com/assets/10601707/14233147/2e0abaf2-f98e-11e5-943d-c70092222883.png)

It seems to me that the icons are causing this. The smaller ones seem 22x22 but are blurry, while the bigger ones seem 32x32 but are perfectly crisp. This seems to indicate that they only come in 32x32 and must be scaled down to fit 22x22. Can you confirm this? There might be a Plasma bug/feature that makes it so Plasma prefers to use 32x32 in this case.

**Comment by beojan** [comment]
Using `identify` tells me they are all 22x22.

**Comment by obnosim** [comment]
Can you open them in Inkscape or a text editor? `identify` only identifies one size even if the file contains several.

Could you attach the icons folder so I can test on my side?

**Comment by beojan** [comment]
As I said earlier, the problem also manifests with the velours icons. That screenshot is below
![image](https://cloud.githubusercontent.com/assets/3727925/14233228/b6568eb4-f9ba-11e5-9cd6-4dec942a71c9.png)

**Comment by obnosim** [comment]
I had a similar problem yesterday when I upgraded my distro and it was caused by a missing package. Reinstalling plasma5-integration-plugin fixed it.

If that's not it, then I have no idea.

**Comment by beojan** [comment]
No such missing package here (I'm using Arch and have plasma-integration installed).

I am using plasma 5.6, so perhaps (if you are using 5.5), this issue is new in plasma 5.6.
Velours is the only theme with such an issue (and perhaps Caledonia, but I haven't tried Caledonia since it disappeared), so the bug is in Velours.

**Comment by obnosim** [comment]
I have been using 5.6 since it went beta (which is how I could add task progress overlays early on) and have not experienced this issue.

You're right, Caledonia seems to have disappeared in the last few days, and Malcer's blog was deleted too. But Caledonia and Velours don't share any artwork or code since well over a year so testing it would be inconclusive.

Just to be sure, delete all plasma_* files in ~/.cache .

**Comment by beojan** [comment]
Done that, still have the issue.

**Comment by obnosim** [comment]
I can only conclude this must be an upstream issue or a local config glitch. Plasma themes have simply no say in icon sizes. Plasma picks the closest in size and stretches it as needed. I am currently using Plasma 5.6.1 and it's working exactly as it did in 5.6.0 and every other version since 5.3.

**Comment by beojan** [comment]
It works in every other theme, so evidently Plasma themes *do* affect icon size.

**Comment by obnosim** [comment]
Are you using Qt 5.6? I have only tried with 5.5.1.

**Comment by beojan** [comment]
Yes, I'm using Qt 5.6.

**Comment by beojan** [comment]
It seems the problem may be that because Velours has thinner borders, the icons jump to the next larger size with a slightly shorter panel than with other themes.

**Comment by obnosim** [comment]
Is this still an issue?

I have upgraded from Qt 5.5 through 5.6.1 and from Plasma 5.6.0 to 5.6.4 and I have never experienced this issue.

Please let me know if it's still happening so I can close the issue if it isn't.

**Comment by beojan** [comment]
It seems to have cleared up now.
